# frozen_string_literal: true

# Generated by core-platform corectl production promotion.
class CorectlNg < Formula
  desc "Core Platform API command-line client (preview)"
  homepage "https://coreplatform.io"
  version "0.0.2"

  on_macos do
    on_arm do
      url "https://ghcr.io/v2/coreeng/corectl/blobs/sha256:2496ec73dbba769a8396835acff66687a70cd922fd8f29d9fd5a6e52e00ee263"
      sha256 "2496ec73dbba769a8396835acff66687a70cd922fd8f29d9fd5a6e52e00ee263"
    end
    on_intel do
      url "https://ghcr.io/v2/coreeng/corectl/blobs/sha256:2e118959ed6a5aec95ecb78073b705c986c92cbbfa8c08f3796b0977e1e087ca"
      sha256 "2e118959ed6a5aec95ecb78073b705c986c92cbbfa8c08f3796b0977e1e087ca"
    end
  end

  on_linux do
    on_arm do
      url "https://ghcr.io/v2/coreeng/corectl/blobs/sha256:7f110b22ad19a934329cf9065b91fa465c903e62bf65f9907d3d6c590c550823"
      sha256 "7f110b22ad19a934329cf9065b91fa465c903e62bf65f9907d3d6c590c550823"
    end
    on_intel do
      url "https://ghcr.io/v2/coreeng/corectl/blobs/sha256:c015f980cc6b0eb36ef6236ac1a8aedf03557dca47d5184d9b190cc10133447d"
      sha256 "c015f980cc6b0eb36ef6236ac1a8aedf03557dca47d5184d9b190cc10133447d"
    end
  end

  def install
    bin.install "corectl" => "corectl-ng"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/corectl-ng version")
    assert_match "get", shell_output("#{bin}/corectl-ng --help")
  end
end
