# frozen_string_literal: true

# Generated by core-platform corectl production promotion.
class Corectl < Formula
  desc "Command-line client for Core Platform"
  homepage "https://coreplatform.io"
  version "0.0.22"
  version_scheme 1

  on_macos do
    on_arm do
      url "https://ghcr.io/v2/coreeng/corectl/blobs/sha256:af3f2dc5d4b5cd7a3d1d190839f66f6e4f77de933a66ebbb15265e16ff549568"
      sha256 "af3f2dc5d4b5cd7a3d1d190839f66f6e4f77de933a66ebbb15265e16ff549568"
    end
    on_intel do
      url "https://ghcr.io/v2/coreeng/corectl/blobs/sha256:5442604eb1cd5a24e565622b4f22ff58590ce76ea800ee64c41d42d9beb5ac33"
      sha256 "5442604eb1cd5a24e565622b4f22ff58590ce76ea800ee64c41d42d9beb5ac33"
    end
  end

  on_linux do
    on_arm do
      url "https://ghcr.io/v2/coreeng/corectl/blobs/sha256:60d50ab2740a7ba78d70ae9d8c23acb9d615228b8d2cce743d5c05a63bb222f2"
      sha256 "60d50ab2740a7ba78d70ae9d8c23acb9d615228b8d2cce743d5c05a63bb222f2"
    end
    on_intel do
      url "https://ghcr.io/v2/coreeng/corectl/blobs/sha256:b90f4bfebcc912721d72d8e6af3fc09b46cb606558578e68e0fc85e5fac22ffd"
      sha256 "b90f4bfebcc912721d72d8e6af3fc09b46cb606558578e68e0fc85e5fac22ffd"
    end
  end

  def install
    bin.install "corectl"
    generate_completions_from_executable(bin/"corectl", "completion")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/corectl version")
    assert_match "get", shell_output("#{bin}/corectl --help")
    assert_path_exists bash_completion/"corectl"
    assert_path_exists zsh_completion/"_corectl"
    assert_path_exists fish_completion/"corectl.fish"
  end
end
