# frozen_string_literal: true

# Generated by core-platform corectl production promotion.
class Corectl < Formula
  desc "Core Platform command-line client"
  homepage "https://coreplatform.io"
  version "0.0.9"
  version_scheme 1

  on_macos do
    on_arm do
      url "https://ghcr.io/v2/coreeng/corectl/blobs/sha256:e45394949ac6b8174f934e58314796f8e6504db18418ee39ad6725790b9a2147"
      sha256 "e45394949ac6b8174f934e58314796f8e6504db18418ee39ad6725790b9a2147"
    end
    on_intel do
      url "https://ghcr.io/v2/coreeng/corectl/blobs/sha256:6f5397407045f3810e5d6769ea09e0f53a0f068910ad7418900aa9251108c690"
      sha256 "6f5397407045f3810e5d6769ea09e0f53a0f068910ad7418900aa9251108c690"
    end
  end

  on_linux do
    on_arm do
      url "https://ghcr.io/v2/coreeng/corectl/blobs/sha256:a65c79d2dbec892fa1ae3b372dff2fc22fe89bb210bfee9a51218761bd9a61ee"
      sha256 "a65c79d2dbec892fa1ae3b372dff2fc22fe89bb210bfee9a51218761bd9a61ee"
    end
    on_intel do
      url "https://ghcr.io/v2/coreeng/corectl/blobs/sha256:35e8d69dc507b85000dce530bd9e57c4ab0cabb8ca9f1a3b630a0d05e3837d60"
      sha256 "35e8d69dc507b85000dce530bd9e57c4ab0cabb8ca9f1a3b630a0d05e3837d60"
    end
  end

  def install
    bin.install "corectl"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/corectl version")
    assert_match "get", shell_output("#{bin}/corectl --help")
  end
end
