# frozen_string_literal: true

# Generated by core-platform corectl production promotion.
class CorectlNg < Formula
  desc "Core Platform API command-line client (preview)"
  homepage "https://coreplatform.io"
  version "0.0.1"

  on_macos do
    on_arm do
      url "https://ghcr.io/v2/coreeng/corectl/blobs/sha256:2fe5f676142c4b90ad50c188661220a241b0e0f076b0e8815e5002fc8befe9e1"
      sha256 "2fe5f676142c4b90ad50c188661220a241b0e0f076b0e8815e5002fc8befe9e1"
    end
    on_intel do
      url "https://ghcr.io/v2/coreeng/corectl/blobs/sha256:63b2f525a6b74f0e97addf800afe2d833b89eea05404f27051c5e8d6febb0e81"
      sha256 "63b2f525a6b74f0e97addf800afe2d833b89eea05404f27051c5e8d6febb0e81"
    end
  end

  on_linux do
    on_arm do
      url "https://ghcr.io/v2/coreeng/corectl/blobs/sha256:4bf1646c422f1f0f2b4c75823775c71c615e70c6f402625b48a1e953ce36f388"
      sha256 "4bf1646c422f1f0f2b4c75823775c71c615e70c6f402625b48a1e953ce36f388"
    end
    on_intel do
      url "https://ghcr.io/v2/coreeng/corectl/blobs/sha256:b90e2fb1033bec358fb775d5c5b1fa72b33203b593971492ac0e2108ef468ed7"
      sha256 "b90e2fb1033bec358fb775d5c5b1fa72b33203b593971492ac0e2108ef468ed7"
    end
  end

  def install
    bin.install "corectl" => "corectl-ng"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/corectl-ng version")
    assert_match "get", shell_output("#{bin}/corectl-ng --help")
  end
end
