# frozen_string_literal: true

# Generated by core-platform corectl production promotion.
class CorectlNg < Formula
  desc "Core Platform API command-line client (preview)"
  homepage "https://coreplatform.io"
  version "0.0.8"

  on_macos do
    on_arm do
      url "https://ghcr.io/v2/coreeng/corectl/blobs/sha256:4272af1ac34912e92e213bd9f6eecf2efdb903d32db98c436f1117c06ef64f05"
      sha256 "4272af1ac34912e92e213bd9f6eecf2efdb903d32db98c436f1117c06ef64f05"
    end
    on_intel do
      url "https://ghcr.io/v2/coreeng/corectl/blobs/sha256:a30c186c5a21d9f0472b044e83b0623ebc7f4e968b808bfaf6688f198bb1d55d"
      sha256 "a30c186c5a21d9f0472b044e83b0623ebc7f4e968b808bfaf6688f198bb1d55d"
    end
  end

  on_linux do
    on_arm do
      url "https://ghcr.io/v2/coreeng/corectl/blobs/sha256:85e69b9330d1815f70ffef688c24351516c72c477962340975dd8c89451d057c"
      sha256 "85e69b9330d1815f70ffef688c24351516c72c477962340975dd8c89451d057c"
    end
    on_intel do
      url "https://ghcr.io/v2/coreeng/corectl/blobs/sha256:bc80222640096215d61f4b6f98e614546e26706f2ebb58e40da3169d4f79ce83"
      sha256 "bc80222640096215d61f4b6f98e614546e26706f2ebb58e40da3169d4f79ce83"
    end
  end

  def install
    bin.install "corectl" => "corectl-ng"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/corectl-ng version")
    assert_match "get", shell_output("#{bin}/corectl-ng --help")
  end
end
