# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Corectl < Formula
  desc "Core Platform CLI"
  homepage "https://github.com/coreeng/corectl"
  version "0.66.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/coreeng/corectl/releases/download/v0.66.2/corectl_Darwin_x86_64.tar.gz"
      sha256 "dd9fb7fb7234bc1c4f597894cbde3259e1f80788c9f901231d302137f36ed779"

      define_method(:install) do
        bin.install "corectl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/coreeng/corectl/releases/download/v0.66.2/corectl_Darwin_arm64.tar.gz"
      sha256 "482d8e6ce3ed52061059f3faa8f0c34c943d0eaf45b11861f40fb24ae6075e03"

      define_method(:install) do
        bin.install "corectl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/coreeng/corectl/releases/download/v0.66.2/corectl_Linux_x86_64.tar.gz"
      sha256 "d77a6995970274ca9eea4414de91ce8a6f30886d01a7061476fb99a7077b813f"
      define_method(:install) do
        bin.install "corectl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/coreeng/corectl/releases/download/v0.66.2/corectl_Linux_arm64.tar.gz"
      sha256 "30f113308b80264666b9a5219376b46f03eb346d868d65825a40db36bc14e05e"
      define_method(:install) do
        bin.install "corectl"
      end
    end
  end
end
