# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SemverUtils < Formula
  desc "CLIs for interactive with semantic versions and semver tags on git repos"
  homepage "https://github.com/coreeng/semver-utils"
  version "0.1.1"

  depends_on "go" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/coreeng/semver-utils/releases/download/v0.1.1/semver-utils_Darwin_x86_64.tar.gz"
      sha256 "b8d5a5e916faed7af5ffc93a708a1765998c5d66a160d23b5fac7032e09b84b8"

      def install
        bin.install "semver"
        bin.install "semver-git"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/coreeng/semver-utils/releases/download/v0.1.1/semver-utils_Darwin_arm64.tar.gz"
      sha256 "0f54daa88b0a575656ad01b412fcf4329b08867560e30bf8d807d17571b75c2d"

      def install
        bin.install "semver"
        bin.install "semver-git"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/coreeng/semver-utils/releases/download/v0.1.1/semver-utils_Linux_x86_64.tar.gz"
      sha256 "af32f1d6746093213018969fd15aa70f95bfeaa76e0968cf762622fc3b64d3fb"
      def install
        bin.install "semver"
        bin.install "semver-git"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/coreeng/semver-utils/releases/download/v0.1.1/semver-utils_Linux_arm64.tar.gz"
      sha256 "a57711acd292564b809d8bef8cb080d2d750ab714075207eb146d278aed29905"
      def install
        bin.install "semver"
        bin.install "semver-git"
      end
    end
  end
end
