# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SemverUtils < Formula
  desc "CLIs for interactive with semantic versions and semver tags on git repos"
  homepage "https://github.com/coreeng/semver-utils"
  version "0.1.4"

  depends_on "go" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/coreeng/semver-utils/releases/download/v0.1.4/semver-utils_Darwin_x86_64.tar.gz"
      sha256 "f770cd709167278cf305475a53103d864b77ca97ae894119b8d66483db42d407"

      def install
        bin.install "semver"
        bin.install "semver-git"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/coreeng/semver-utils/releases/download/v0.1.4/semver-utils_Darwin_arm64.tar.gz"
      sha256 "7adbff5a4db4e2cf8855b8d3d2261c53bb5d0fe693b2a083d821be20adbad03a"

      def install
        bin.install "semver"
        bin.install "semver-git"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/coreeng/semver-utils/releases/download/v0.1.4/semver-utils_Linux_x86_64.tar.gz"
      sha256 "38d3f0e84e975659ff7cc0a2e5931faf237fcb46421f06884d8a0d5db9e28341"
      def install
        bin.install "semver"
        bin.install "semver-git"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/coreeng/semver-utils/releases/download/v0.1.4/semver-utils_Linux_arm64.tar.gz"
      sha256 "70377a98b45b5befdbb3aa8ed1a7860291f623d29ff1affd060096c0fadeaf3f"
      def install
        bin.install "semver"
        bin.install "semver-git"
      end
    end
  end
end
