# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tpm < Formula
  desc "Training Platform Module (tpm) CLI — author and manage training modules and labs"
  homepage "https://github.com/coreeng/tpm"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/coreeng/tpm/releases/download/v0.2.0/tpm_0.2.0_darwin_amd64.tar.gz"
      sha256 "48074c71b62c197a58357361668da2ca21a97df4999ca73838a443dfaeb6bf47"

      define_method(:install) do
        bin.install "tpm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/coreeng/tpm/releases/download/v0.2.0/tpm_0.2.0_darwin_arm64.tar.gz"
      sha256 "2ca86f245dc012408676ee320c0c68aca0c9519ebd2ce1caa3afc92fd83d14fd"

      define_method(:install) do
        bin.install "tpm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/coreeng/tpm/releases/download/v0.2.0/tpm_0.2.0_linux_amd64.tar.gz"
      sha256 "c20ccf82a1c22048c720fd516ab078d201b38d85a0076febe8d9ad0f45812bb2"
      define_method(:install) do
        bin.install "tpm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/coreeng/tpm/releases/download/v0.2.0/tpm_0.2.0_linux_arm64.tar.gz"
      sha256 "a3bb37b97d898a9392c7b19094fd739c88f7d5d5d2234d0c5ece961596610107"
      define_method(:install) do
        bin.install "tpm"
      end
    end
  end
end
